version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - ${CA_CERT_PATH}:${CA_CERT_PATH}
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: require
      CA_CERT_PATH: ${CA_CERT_PATH}
    ports:
      - "8501:8501"
    networks:
      - datasharing
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ${CA_CERT_PATH}:${CA_CERT_PATH}
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: require
      CA_CERT_PATH: ${CA_CERT_PATH}
    networks:
      - datasharing
    env_file:
      - .env

networks:
  datasharing:
